// Package resource_access provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package resource_access

import (
	core "github.com/meshery/schemas/models/core"
)

// Actor One grant or revoke target in a ResourceAccessMappingPayload.
type Actor struct {
	// ActorId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ActorId core.Uuid `json:"actorId" yaml:"actorId"`

	// ActorType Kind of actor. Every known client sends user; the server field is a plain string with no enforced enum, so this is modelled as an open string rather than an enum of one value that would reject a legitimate future actor type (for example a team or a service account) before the server itself does.
	ActorType string `json:"actorType" yaml:"actorType"`
}

// ResourceAccessMappingPayload Request body for POST /api/resources/{resourceType}/{resourceId}/share. Every field is required because the only confirmed-correct client always sends all three; a request missing one has not been verified against the server's actual decode behavior for a missing key, only for a differently-named one, which the server accepts and silently drops (see the parent issue this construct was added for).
type ResourceAccessMappingPayload struct {
	// GrantAccess Actors to grant access to. May be empty.
	GrantAccess []Actor `json:"grantAccess" yaml:"grantAccess"`

	// NotifyUsers Whether to notify the affected actors of the change.
	NotifyUsers bool `json:"notifyUsers" yaml:"notifyUsers"`

	// RevokeAccess Actors to revoke access from. May be empty.
	RevokeAccess []Actor `json:"revokeAccess" yaml:"revokeAccess"`
}

// ResourceId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type ResourceId = core.Uuid

// ResourceType defines model for resourceType.
type ResourceType = string
